#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                on
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xffde4a96
yabai -m config normal_window_border_color   0xff1c2f45
yabai -m config insert_feedback_color        0xffefc03d
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
#yabai -m config external_bar                 all:$(spacebar -m config height):0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# space naming
yabai -m space 1 --label web
yabai -m space 2 --label term
yabai -m space 3 --label work
yabai -m space 4 --label music
yabai -m space 5 --label mail
yabai -m space 6 --label chat
yabai -m space 7 --label calendar

# app specifics
yabai -m rule --add app="^ueli" layer=above manage=off
yabai -m rule --add app="^Calculator" layer=above manage=off
yabai -m rule --add app="^zoom.us" layer=above manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^Stickies$" layer=above manage=off
yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  app='^Brave Browser$' \
  title='^MetaMask Notification$' \
  action='
    yabai -m query --windows --window $YABAI_WINDOW_ID \
    | jq -re ".floating == 0" \
    && yabai -m window $YABAI_WINDOW_ID --toggle float
  '
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^VLC$" manage=off


# signals
yabai -m signal --add event=space_changed action="sh ~/.config/yabai/scripts/clean_empty_spaces.sh"


echo "yabai configuration loaded.."

